# Generated by Django 5.2.7 on 2025-10-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_on', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=100, null=True)),
                ('mode_of_pay', models.CharField(blank=True, max_length=20, null=True)),
                ('mat_inspected', models.CharField(blank=True, max_length=100, null=True)),
                ('mat_received', models.CharField(blank=True, max_length=100, null=True)),
                ('process_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('process_approve', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='accountent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role_type', models.CharField(default='accountent', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role_type', models.CharField(default='Admin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role_type', models.CharField(default='product', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role_type', models.CharField(default='QA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='role1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role_type', models.CharField(default='role1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_date', models.DateField(blank=True, null=True)),
                ('planning_date', models.DateField(blank=True, null=True)),
                ('date_of_inspection', models.DateField(blank=True, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plan_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_no', models.CharField(blank=True, max_length=30, null=True)),
                ('lm_co1', models.BooleanField(default=False)),
                ('lm_co2', models.BooleanField(default=False)),
                ('lm_co3', models.BooleanField(default=False)),
                ('fm_co1', models.BooleanField(default=False)),
                ('fm_co2', models.BooleanField(default=False)),
                ('fm_co3', models.BooleanField(default=False)),
                ('status', models.CharField(default='incomplete', max_length=20)),
                ('product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='product_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='product_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BooleanField(blank=True, max_length=30, null=True)),
                ('Thick', models.BooleanField(blank=True, max_length=30, null=True)),
                ('Grade', models.BooleanField(blank=True, max_length=30, null=True)),
                ('Drawing', models.BooleanField(blank=True, max_length=30, null=True)),
                ('Test_Certificate', models.BooleanField(blank=True, max_length=30, null=True)),
                ('product_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_material')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField()),
                ('cycle_time', models.TimeField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('product_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan_product')),
                ('schedule_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
        ),
    ]
