# Generated by Django 5.2.7 on 2025-10-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountent_admin_product_qa_role1_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountent',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role1',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
