# Generated by Django 4.2.25 on 2025-10-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accountent_email_admin_email_product_email_qa_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('material_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BooleanField(default=False)),
                ('Thick', models.BooleanField(default=False)),
                ('Grade', models.BooleanField(default=False)),
                ('Drawing', models.BooleanField(default=False)),
                ('Test_Certificate', models.BooleanField(default=False)),
            ],
        ),
    ]
