# Generated by Django 4.2.25 on 2025-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
