# Generated by Django 4.2.25 on 2025-10-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_no', models.CharField(blank=True, max_length=30, null=True)),
                ('lm_co1', models.BooleanField(default=False)),
                ('lm_co2', models.BooleanField(default=False)),
                ('lm_co3', models.BooleanField(default=False)),
                ('fm_co1', models.BooleanField(default=False)),
                ('fm_co2', models.BooleanField(default=False)),
                ('fm_co3', models.BooleanField(default=False)),
            ],
        ),
    ]
