# Generated by Django 4.2.25 on 2025-10-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plan_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_product',
            name='product_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details'),
        ),
    ]
