# Generated by Django 4.2.25 on 2025-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plan_product_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='status',
            field=models.CharField(blank=True, default='incomplete', max_length=30, null=True),
        ),
    ]
