# Generated by Django 4.2.25 on 2025-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='Drawing',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Test_Certificate',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Thick',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='material_Description',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='size',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
