# Generated by Django 4.2.25 on 2025-10-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_details_drawing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('Thick', models.CharField(blank=True, max_length=30, null=True)),
                ('Grade', models.CharField(blank=True, max_length=30, null=True)),
                ('Drawing', models.CharField(blank=True, max_length=30, null=True)),
                ('Test_Certificate', models.CharField(blank=True, max_length=30, null=True)),
                ('product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
    ]
