# Generated by Django 4.2.25 on 2025-10-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_material',
            name='Drawing',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='Test_Certificate',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='Thick',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='size',
        ),
        migrations.CreateModel(
            name='product_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('Thick', models.CharField(blank=True, max_length=30, null=True)),
                ('Grade', models.CharField(blank=True, max_length=30, null=True)),
                ('Drawing', models.CharField(blank=True, max_length=30, null=True)),
                ('Test_Certificate', models.CharField(blank=True, max_length=30, null=True)),
                ('product_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_material')),
            ],
        ),
    ]
