# Generated by Django 4.2.25 on 2025-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_accountent_password_alter_accountent_role_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_on', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=100, null=True)),
                ('mode_of_pay', models.CharField(blank=True, max_length=20, null=True)),
                ('mat_inspected', models.CharField(blank=True, max_length=100, null=True)),
                ('mat_received', models.CharField(blank=True, max_length=100, null=True)),
                ('process_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('process_approve', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_date', models.DateField(auto_now_add=True)),
                ('planning_date', models.DateField(auto_now_add=True)),
                ('date_of_inspection', models.DateField(auto_now_add=True)),
                ('date_of_delivery', models.DateField(auto_now_add=True)),
                ('process_date', models.DateField(auto_now_add=True)),
                ('cycle_time', models.TimeField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan_product',
            name='status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
    ]
